### ISSUE TITLE
Error: Invalid public key

### ISSUE THREAD

**Issue by kevinhf35** [ylmenezes/php-juno-v2#1]
Boa noite Yan

Baixei o arquivos, subi pro server, alterei o config com o token publico, client id e o clientsecrett mas quando executo a index continua me informando que "Error: Invalid public key", sabe me dizer o que esta ocorrendo?

**Comment by kevinhf35** [comment]
Opa tudo bom Yan? Sigo na luta aqui rs, será que você conseguiria me dar um norte? rs

**Comment by ylmenezes** [comment]
Desculpe a demora, estou em conclusão de um job.
Vi que conseguiu respondendo um colega de profissão.

Então creio que solucionou o problema, correto? 

> Boa noite Yan
> 
> Baixei o arquivos, subi pro server, alterei o config com o token publico, client id e o clientsecrett mas quando executo a index continua me informando que "Error: Invalid public key", sabe me dizer o que esta ocorrendo?

**Comment by kevinhf35** [comment]
Opa eai @ylmenezes 

Tranquilo rs, deu certo sim, vlw pela ajuda!
Estou agora vendo uma documentação pra fazer a integração com PIX deles, você já fez algo sobre isso?

**Comment by lpex-code** [comment]
Boa tarde!

Também estou com o erro:  "Error: Invalid public key"

$base64 = base64_encode("{$clientId}:{$clientSecret}");
$token         = 'Basic {$base64}';

Na outra documetanção falam sobre a geração esta forma..
como seria?

**Comment by lpex-code** [comment]
> Boa tarde!
> 
> Também estou com o erro: "Error: Invalid public key"
> 
> $base64 = base64_encode("{$clientId}:{$clientSecret}");
> $token = 'Basic {$base64}';
> 
> Na outra documetanção falam sobre a geração esta forma..
> como seria?

Experimentei também com o token privado e token público gerado nas credenciais. Nenhuma das 3 formas deu certo.

**Comment by ylmenezes** [comment]
> > Boa tarde!
> > Também estou com o erro: "Error: Invalid public key"
> > $base64 = base64_encode("{$clientId}:{$clientSecret}");
> > $token = 'Basic {$base64}';
> > Na outra documetanção falam sobre a geração esta forma..
> > como seria?
> 
> Experimentei também com o token privado e token público gerado nas credenciais. Nenhuma das 3 formas deu certo.

Bom dia @lpex-code , blz dev? 

Verifica se está no ambiente sandbox ou produção, nesses caso precisa passar o parâmetro False/True.

Sendo que true habilita o modo sandbox e false fica em produção.

**Comment by kevinhf35** [comment]
Opa eai @ylmenezes blz?

To tentando criar uma classe adicional para pix, mas não sei se estou fazendo da forma correta rs... Acho que seria interessante colocar o PIX na sua classe não acha?

Isso é o que estou tentando:

    public function createPix()
    {
        try{

            $data = array(
                'devedor' => [
                    'cpf'           =>  $this->cpf,
                    'nome'          =>  $this->nome,
                ],
                'calendario' => [
                    'expiracao'     =>  3600,
                ],
                'valor' => [
                    'original'     =>  $this->original,
                ],
                'chave' => "7d9f0335-8dcc-4054-9bf9-0dbd61d36906",
                'solicitacaoPagador' => $this->solicitacaoPagador,
                //'txid' => "7978c0c97ea847e78e8849634473c1f1",

            );

            $aCharge = $this->request( 'pix-api/v2/cob/7978c0c97ea847e78e8849634473c1f1', 'PUT', $data);
            if( $aCharge->status ){
                throw new Exception( $aCharge->details[0]->message );
            }else{
                return $aCharge;
            }
        }catch(Exception $e){
          $this->exception($e);
        }
    }

**Comment by ylmenezes** [comment]
> Opa eai @ylmenezes blz?
> 
> To tentando criar uma classe adicional para pix, mas não sei se estou fazendo da forma correta rs... Acho que seria interessante colocar o PIX na sua classe não acha?
> 
> Isso é o que estou tentando:
> 
> ```
> public function createPix()
> {
>     try{
> 
>         $data = array(
>             'devedor' => [
>                 'cpf'           =>  $this->cpf,
>                 'nome'          =>  $this->nome,
>             ],
>             'calendario' => [
>                 'expiracao'     =>  3600,
>             ],
>             'valor' => [
>                 'original'     =>  $this->original,
>             ],
>             'chave' => "7d9f0335-8dcc-4054-9bf9-0dbd61d36906",
>             'solicitacaoPagador' => $this->solicitacaoPagador,
>             //'txid' => "7978c0c97ea847e78e8849634473c1f1",
> 
>         );
> 
>         $aCharge = $this->request( 'pix-api/v2/cob/7978c0c97ea847e78e8849634473c1f1', 'PUT', $data);
>         if( $aCharge->status ){
>             throw new Exception( $aCharge->details[0]->message );
>         }else{
>             return $aCharge;
>         }
>     }catch(Exception $e){
>       $this->exception($e);
>     }
> }
> ```

Show @kevinhf35 , cria uma branch no projeto e vamos trabalhar juntos na ideia. 
Caso já tenha concluído eu baixo para fazer um pull request na master.

O que passou no exemplo acima é essa a ideia mesmo .

**Comment by kevinhf35** [comment]
Então na verdade eu parei por aqui hahah tentei fazer a outra modalidade de PIX sem txid, mas também não rolou =/ (na documentação tem duas modalidades uma com txid e outra direto, pelo que vi uma você vai conseguir ter o retorno uma vez que gera o ID da cobrança e a outra é fixa), não sou mto familiarizado com o github rs uso mais o stack mesmo, se voce me der um norte eu posso fazer o script e depois te mando por aqui =P

**Comment by kevinhf35** [comment]
Opa eai @ylmenezes muito corrido por ai? rs o que achou da idéia?

**Comment by ylmenezes** [comment]
> Opa eai @ylmenezes muito corrido por ai? rs o que achou da idéia?

Bom dia!
@kevinhf35  vamos abri uma nova issue para tratar do pix. 
Vou trabalhar me cima do me passou e implementar.
